"""兼容入口：请优先 ``from services.qa import QaService``。

保留 ``from services.qa_service import X``；测试 patch 请打到
``services.qa.helpers`` / ``services.qa.service`` 上的真实符号。
"""

from config.database import AsyncSessionLocal
from config.env import LangfuseConfig
from services.chat_service import ChatService
from services.qa.helpers import (  # noqa: F401
    ACTIVE_STREAMS,
    _ActiveStreamState,
    _assistant_content_for_persist,
    _assistant_content_snapshot,
    _assistant_status_for_finish,
    _build_assistant_persist_extra,
    _finalize_sse_bridge_stream,
    _finalize_streaming_assistant,
    _flush_ctx_text_buffer,
    _handle_stream_client_disconnect,
    _insert_streaming_assistant_skeleton,
    _langfuse_stream_context,
    _mark_stream_persist_finalized,
    _new_stream_ctx,
    _normalize_id_list,
    _normalize_kb_collections,
    _normalize_model_id,
    _persist_assistant,
    _persist_disconnect_partial,
    _persist_hitl_pending_assistant,
    _persist_session_context_snapshot,
    _persist_stream_checkpoint,
    _register_active_stream,
    _resolve_assistant_message_id,
    _resolve_enabled_skills_for_query,
    _resolve_kb_settings_for_query,
    _resolve_mcp_servers_for_query,
    _resolve_model_for_query,
    _resolved_model_name,
    _run_orchestrator,
    _stream_terminal_persist_done,
    _unregister_active_stream,
    _yield_sse_from_agent_bridge,
    case_coordinator,
    common_agent,
    fault_agent,
    super_agent,
)
from services.qa.service import QaService

__all__ = [
    "ACTIVE_STREAMS",
    "AsyncSessionLocal",
    "ChatService",
    "LangfuseConfig",
    "QaService",
    "_ActiveStreamState",
    "_assistant_content_for_persist",
    "_assistant_content_snapshot",
    "_assistant_status_for_finish",
    "_build_assistant_persist_extra",
    "_finalize_sse_bridge_stream",
    "_finalize_streaming_assistant",
    "_flush_ctx_text_buffer",
    "_handle_stream_client_disconnect",
    "_insert_streaming_assistant_skeleton",
    "_langfuse_stream_context",
    "_mark_stream_persist_finalized",
    "_new_stream_ctx",
    "_normalize_id_list",
    "_normalize_kb_collections",
    "_normalize_model_id",
    "_persist_assistant",
    "_persist_disconnect_partial",
    "_persist_hitl_pending_assistant",
    "_persist_session_context_snapshot",
    "_persist_stream_checkpoint",
    "_register_active_stream",
    "_resolve_assistant_message_id",
    "_resolve_enabled_skills_for_query",
    "_resolve_kb_settings_for_query",
    "_resolve_mcp_servers_for_query",
    "_resolve_model_for_query",
    "_resolved_model_name",
    "_run_orchestrator",
    "_stream_terminal_persist_done",
    "_unregister_active_stream",
    "_yield_sse_from_agent_bridge",
    "case_coordinator",
    "common_agent",
    "fault_agent",
    "super_agent",
]
