"""Use native UUIDv7-compatible identifiers for users and ownership columns.

Revision ID: 202608240002
Revises: 202608240001
Create Date: 2026-08-24

Existing integer users are assigned deterministic UUIDs during the migration
so old rows keep their ownership. New users are generated by the application
with UUIDv7.
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa

from noesis.ids import new_uuid7

revision = "202608240002"
down_revision = "202608240001"
branch_labels = None
depends_on = None


_STRING_USER_TABLES = (
    "t_chat_session",
    "t_chat_message",
    "t_chat_attachment",
    "t_agent_run",
    "t_bg_task",
    "t_memory_user_preference",
    "t_memory_run_snapshot",
    "t_memory_item",
    "t_memory_evidence",
    "t_memory_relation",
    "t_memory_job",
    "t_memory_outbox",
    "t_memory_query_trace",
)

_INTEGER_USER_TABLES = (
    "t_user_session",
    "user_scheduled_tasks",
    "user_scheduled_task_runs",
    "user_notification_preferences",
    "user_settings_audit",
    "user_llm_providers",
    "user_llm_models",
)


def _collect_legacy_ids() -> None:
    op.execute(
        sa.text(
            """
            CREATE TEMP TABLE _noesis_user_id_map (
                legacy_user_id TEXT PRIMARY KEY,
                user_uuid UUID NOT NULL
            ) ON COMMIT DROP
            """
        )
    )
    op.execute(
        sa.text(
            """
            INSERT INTO _noesis_user_id_map (legacy_user_id, user_uuid)
            SELECT id::text, md5('noesis-user:' || id::text)::uuid
            FROM t_user
            ON CONFLICT (legacy_user_id) DO NOTHING
            """
        )
    )
    for table in _STRING_USER_TABLES:
        op.execute(
            sa.text(
                f"""
                INSERT INTO _noesis_user_id_map (legacy_user_id, user_uuid)
                SELECT DISTINCT user_id::text, md5('noesis-user:' || user_id::text)::uuid
                FROM {table}
                WHERE user_id IS NOT NULL
                ON CONFLICT (legacy_user_id) DO NOTHING
                """
            )
        )
    # The seeded admin is the only user created by the legacy bootstrap.
    # Give it a real UUIDv7 instead of keeping the compatibility UUID derived
    # from the old integer primary key.
    op.execute(
        sa.text(
            """
            UPDATE _noesis_user_id_map AS mapping
            SET user_uuid = CAST(:admin_uuid AS uuid)
            FROM t_user AS user_row
            WHERE user_row.username = 'admin'
              AND mapping.legacy_user_id = user_row.id::text
            """
        ).bindparams(admin_uuid=new_uuid7())
    )


def _convert_t_user() -> None:
    op.execute(
        sa.text(
            """
            ALTER TABLE t_user ADD COLUMN __noesis_user_uuid UUID
            """
        )
    )
    op.execute(
        sa.text(
            """
            UPDATE t_user AS u
            SET __noesis_user_uuid = m.user_uuid
            FROM _noesis_user_id_map AS m
            WHERE m.legacy_user_id = u.id::text
            """
        )
    )
    op.execute(sa.text("ALTER TABLE t_user DROP CONSTRAINT t_user_pkey"))
    op.execute(sa.text("ALTER TABLE t_user DROP COLUMN id"))
    op.execute(sa.text("ALTER TABLE t_user RENAME COLUMN __noesis_user_uuid TO id"))
    op.execute(sa.text("ALTER TABLE t_user ADD CONSTRAINT t_user_pkey PRIMARY KEY (id)"))


def _convert_user_id_column(table: str) -> None:
    op.execute(sa.text(f"ALTER TABLE {table} ADD COLUMN __noesis_user_uuid UUID"))
    op.execute(
        sa.text(
            f"""
            UPDATE {table} AS target
            SET __noesis_user_uuid = mapping.user_uuid
            FROM _noesis_user_id_map AS mapping
            WHERE mapping.legacy_user_id = target.user_id::text
            """
        )
    )
    op.execute(
        sa.text(
            f"""
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM {table} WHERE __noesis_user_uuid IS NULL) THEN
                    RAISE EXCEPTION 'cannot map legacy user_id values in {table}';
                END IF;
            END $$
            """
        )
    )
    op.execute(sa.text(f"ALTER TABLE {table} DROP COLUMN user_id"))
    op.execute(sa.text(f"ALTER TABLE {table} RENAME COLUMN __noesis_user_uuid TO user_id"))
    op.execute(sa.text(f"ALTER TABLE {table} ALTER COLUMN user_id SET NOT NULL"))


def _restore_indexes_and_constraints() -> None:
    op.create_primary_key("t_memory_user_preference_pkey", "t_memory_user_preference", ["user_id"])
    op.create_index("ix_t_user_session_user_id", "t_user_session", ["user_id"])
    op.create_index(
        "idx_user_session_user_active",
        "t_user_session",
        ["user_id", "revoked_at", "idle_expires_at"],
    )
    op.create_index("idx_session_user", "t_chat_session", ["user_id"])
    op.create_index("idx_session_user_archived", "t_chat_session", ["user_id", "archived"])
    op.create_index("idx_user_scheduled_tasks_user", "user_scheduled_tasks", ["user_id"])
    op.create_index(
        "idx_user_scheduled_task_runs_task",
        "user_scheduled_task_runs",
        ["user_id", "task_id", "created_at"],
    )
    op.create_unique_constraint(
        "uq_user_task_run_idempotency",
        "user_scheduled_task_runs",
        ["user_id", "idempotency_key"],
    )
    op.create_unique_constraint(
        "uq_user_notification_preference",
        "user_notification_preferences",
        ["user_id", "event_type", "delivery_surface"],
    )
    op.create_index(
        "idx_user_notification_preferences_user",
        "user_notification_preferences",
        ["user_id"],
    )
    op.create_index("idx_user_settings_audit_user_time", "user_settings_audit", ["user_id", "created_at"])
    op.create_index("idx_user_llm_providers_user", "user_llm_providers", ["user_id"])
    op.create_index("idx_user_llm_models_user", "user_llm_models", ["user_id"])
    op.create_index(
        "uq_user_llm_models_user_model",
        "user_llm_models",
        ["user_id", "model_id"],
        unique=True,
    )
    op.create_unique_constraint(
        "uq_agent_run_user_request",
        "t_agent_run",
        ["user_id", "client_request_id"],
    )
    op.create_foreign_key("fk_t_user_session_user", "t_user_session", "t_user", ["user_id"], ["id"], ondelete="CASCADE")
    op.create_foreign_key("fk_user_scheduled_tasks_user", "user_scheduled_tasks", "t_user", ["user_id"], ["id"], ondelete="CASCADE")
    op.create_foreign_key("fk_user_scheduled_task_runs_user", "user_scheduled_task_runs", "t_user", ["user_id"], ["id"], ondelete="CASCADE")
    op.create_foreign_key("fk_user_notification_preferences_user", "user_notification_preferences", "t_user", ["user_id"], ["id"], ondelete="CASCADE")
    op.create_foreign_key("fk_user_settings_audit_user", "user_settings_audit", "t_user", ["user_id"], ["id"])
    op.create_foreign_key("fk_user_llm_providers_user", "user_llm_providers", "t_user", ["user_id"], ["id"], ondelete="CASCADE")
    op.create_foreign_key("fk_user_llm_models_user", "user_llm_models", "t_user", ["user_id"], ["id"], ondelete="CASCADE")
    op.create_index("idx_memory_snapshot_user_scope", "t_memory_run_snapshot", ["user_id", "scope_key", "captured_at"])
    op.create_index(
        "uq_memory_item_current_identity",
        "t_memory_item",
        ["user_id", "scope_key", "memory_type", "subject_key"],
        unique=True,
        postgresql_where=sa.text("status <> 'superseded'"),
    )
    op.create_index("idx_memory_item_retrieval", "t_memory_item", ["user_id", "scope_key", "status", "memory_type"])
    op.create_index("idx_memory_relation_user", "t_memory_relation", ["user_id", "source_item_id"])
    op.create_index("idx_memory_job_health", "t_memory_job", ["user_id", "status", "updated_at"])
    op.create_index(
        "idx_memory_query_trace_user",
        "t_memory_query_trace",
        ["user_id", "created_at"],
    )


def upgrade() -> None:
    _collect_legacy_ids()

    # Keep the JSON copy used by older chat code consistent with the new ID.
    op.execute(
        sa.text(
            """
            UPDATE t_chat_session AS s
            SET extra = jsonb_set(
                s.extra::jsonb,
                '{user_id}',
                to_jsonb(mapping.user_uuid::text),
                false
            )
            FROM _noesis_user_id_map AS mapping
            WHERE jsonb_typeof(s.extra::jsonb) = 'object'
              AND s.extra::jsonb ? 'user_id'
              AND mapping.legacy_user_id = s.extra::jsonb->>'user_id'
            """
        )
    )

    _convert_t_user()
    for table in _INTEGER_USER_TABLES + _STRING_USER_TABLES:
        _convert_user_id_column(table)
    _restore_indexes_and_constraints()


def downgrade() -> None:
    if op.get_context().as_sql:
        return
    raise RuntimeError("UUID user IDs are intentionally irreversible; reset the database instead")
