"""Persistence ports required by authentication application services."""

from __future__ import annotations

from typing import Protocol

from noesis.domain.auth.entities import AuthSession, AuthUser


class UserRepository(Protocol):
    async def get_by_id(self, user_id: int) -> AuthUser | None: ...
    async def get_by_username(self, username: str) -> AuthUser | None: ...
    async def get_invite_owner(self) -> AuthUser | None: ...
    async def add(self, user: AuthUser) -> AuthUser: ...
    async def save(self, user: AuthUser) -> None: ...


class SessionRepository(Protocol):
    async def get_by_digest(self, session_digest: str) -> AuthSession | None: ...
    async def get_by_id_for_user(self, session_id: str, user_id: int) -> AuthSession | None: ...
    async def add(self, session: AuthSession) -> AuthSession: ...
    async def save(self, session: AuthSession) -> None: ...
    async def revoke_all(self, user_id: int, revoked_at: int) -> None: ...
    async def list_active(self, user_id: int, now_ms: int) -> list[AuthSession]: ...
